theme: jekyll-theme-minimal
# Site settings
title: You Blog                     #你博客的标题
SEOTitle: 你的博客 | You Blog        #显示在浏览器上搜索的时候显示的标题
header-img: img/1.jpg     #显示在首页的背景图片
email: 335188567@qq.com    
description: "You Blog"              #网站介绍
keyword: "BY, BY Blog, 吴东林的博客, wudonglin, 吴东林, iOS, Apple, iPhone" #关键词
url: "https://dong1in.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写
# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "这是吴东林的个人博客"
